### ISSUE TITLE
Making clygments an optional dependency

### ISSUE THREAD

**Issue by elken** [cjohansen/powerpack#1]
(This probably makes more sense to be a discussion, but discussions aren't enabled)

I agree with the README note that this should be optional, for my usage I'll end up using prisma since it includes more than just syntax highlighting. I can also imagine general static sites might not include code blocks (I suppose the same could be argued for imagine etc, but those are much lighter)

It also caused a very nasty exception on startup that was very hard to debug, turned out the container I was running in didn't have python installed.

Thanks again for powerpack! This is _exactly_ what I needed

**Comment by cjohansen** [comment]
Ah, too bad that caused such a bad experience for you. I had forgotten to decide on this before doing the public release 🙈 I'll make the dependency optional!

**Comment by cjohansen** [comment]
I was a little quick 😅 Powerpack also uses highlighting during development to report errors... I can make that optional so it's easier to remove clygments.

Curious: which prisma are talking about?

**Comment by cjohansen** [comment]
I'm sorry, I need to have a closer look at this. I'd like the development experience to work as is, without forcing people to use a python dependency... Open to suggestions!

**Comment by elken** [comment]
> Curious: which prisma are talking about?

https://prismjs.com/index.html Prism not Prisma sorry

> I'm sorry, I need to have a closer look at this. I'd like the development experience to work as is, without forcing people to use a python dependency... Open to suggestions!

Ah the little error windows? Highlight.js or prism should work

**Comment by cjohansen** [comment]
Ah, right. I've used Prism before, it's good for small stuff :) I changed the HUD to use that, and released 2024.01.05, which no longer depends on clygments.

**Comment by elken** [comment]
Great stuff! Thanks again
