### ISSUE TITLE
Strange behaviour with Prism

### ISSUE THREAD

**Issue by elken** [cjohansen/powerpack#2]
So I've been trying to resolve this myself and I'm not getting very far.

I'm working on moving my blog to [powerpack](https://github.com/elken/dev/tree/feat/powerpack) and I've hit a final snag with Prismjs integration.

I've tried replicating it in the powerblog demo and all seems to work there, so there must be something wrong with what I have...

Basically, Prism seems to "load" well enough to produce the below

![image](https://github.com/cjohansen/powerpack/assets/2872862/bc89d990-3ab1-4212-899f-b88c0631ac57)

But none of the included plugins load.

I've generated my Prism setup from [this](https://prismjs.com/download.html#themes=prism&languages=css+clojure+lisp&plugins=line-highlight+line-numbers+autolinker+show-language+previewers+autoloader+command-line+normalize-whitespace+data-uri-highlight+toolbar+copy-to-clipboard+match-braces+diff-highlight), and as such there are a number of plugins that should show up (namely line numbers)

The file complains about various aspects being missing that should have been added in previous lines; almost like the lines are being run either out of order or in another context and I cannot for the _life_ of me work out why that's the case. If I add a `console.log(Prism.plugins)` in the prismjs file, that prints out everything fine; but the actual `Prism.plugins` is empty, so this is leading me to think that it's running on a different context for some unknown reason.

By making the below changes to powerblog, this seems to apply the plugins just fine.

```diff
modified   content/index.md
@@ -6,3 +6,11 @@
 
 You have reached the Powerblog, the highly fictitious blog that simply exists to
 showcase [Powerpack](https://github.com/cjohansen/powerpack).
+
+```clojure
+(defn add-1 [x]
+  (inc x))
+  
+(println (add-1 5))
+;; => 6
+```
modified   src/powerblog/core.clj
@@ -15,7 +15,11 @@
 
    :optimus/bundles {"app.css"
                      {:public-dir "public"
-                      :paths ["/styles.css"]}}
+                      :paths ["/styles.css"
+                              "/prism.css"]}
+                     "prism.js"
+                     {:public-dir "public"
+                      :paths ["/prism.min.js"]}}
 
    :optimus/assets [{:public-dir "public"
                      :paths [#".*\.jpg"]}]
modified   src/powerblog/layout.clj
@@ -4,7 +4,7 @@
   [:html.dark:bg-zinc-900
    [:head
     (when title [:title title])]
-   [:body.py-8
+   [:body.py-8.line-numbers.match-braces.rainbow-braces
     content]])
 
 (def header
```

Hopefully we can get to the bottom of this :sweat_smile: Thanks!

**Comment by cjohansen** [comment]
This is definitely Powerpack's version of Prism messing you up 😅 Updating the Powerpack version in Powerblog's deps.edn reproduces the problem. I tried to avoid that, but obviously failed. Will see if I can figure it out.

**Comment by elken** [comment]
Ahh that makes a ton of sense actually! I caused my own demise :rofl: 

You could do some kind of regex in the internal version of prism to use a different object to `Prism` maybe?

**Comment by cjohansen** [comment]
I did stick it in an IIFE, but it broke out... I hadn't looked closely enough at the code.

**Comment by cjohansen** [comment]
2024.01.08 should fix your problems. Sorry about that 😊

**Comment by elken** [comment]
Ah I still have a minor issue but it seems CSS related at least, confirmed as fixed!
