### ISSUE TITLE
Support for pulling opengraph images from an endpoint

### ISSUE THREAD

**Issue by elken** [cjohansen/powerpack#3]
Me again :sweat_smile: 

Recently I had the idea to build custom opengraph images like how github handles repo ones; but `:open-graph/image` pulls directly from the imagine config ([context](https://github.com/cjohansen/powerpack/blob/d3d40db42d858717de34cffd329c8b646972986c/src/powerpack/hiccup.clj#L58-L65)) so an endpoint here wouldn't work.

Is there a nice middleground here or is there a need for an `:open-graph/image-endpoint`; or rather than ingesting my files in `on-ingested` should I just generate the files then?

**Comment by cjohansen** [comment]
That's a bad assumption, Powerpack should check if the image URL is qualified and if so leave it unprocessed. Will fix, hopefully tomorrow.

**Comment by elken** [comment]
No rush! Thanks :smile:

**Comment by cjohansen** [comment]
Fixed in 2024.01.14
